class CreateSiteContents < ActiveRecord::Migration
  def change
    create_table :site_contents do |t|
      t.text :livestock_results_notices_charolais
      t.text :livestock_results_notices_dairy
      t.text :livestock_results_notices_bb
      t.text :livestock_results_notices_aa
      t.text :livestock_results_notices_lleyn
      t.text :livestock_results_about
      t.string :booking_show_forms_pp_url
      t.string :booking_show_forms_lm_url
      t.string :booking_show_forms_eg_internal_url
      t.string :booking_show_forms_eg_external_url
      t.string :booking_show_forms_nec_url
      t.string :booking_show_forms_alcohol_url
      t.string :booking_show_forms_food_url
      t.text :booking_start
      t.string :registration_sponsor_icon
      t.text :registration_sponsor_text
      t.text :registration_help
      t.text :cattle_tb
      t.string :livestock_contact_name
      t.string :livestock_contact_org
      t.string :livestock_contact_street
      t.string :livestock_contact_locality
      t.string :livestock_contact_region
      t.string :livestock_contact_postcode
      t.string :livestock_contact_country
      t.text :livestock_nlsc_info
      t.string :accommodation_one
      t.text :accommodation_one_about
      t.string :accommodation_two
      t.text :accommodation_two_about
      t.string :awards_1_name
      t.text :awards_1_about
      t.text :awards_1_lastyear
      t.string :awards_1_lastyear_image_url
      t.text :awards_1_conditions
      t.string :awards_2_name
      t.text :awards_2_about
      t.text :awards_2_lastyear
      t.string :awards_2_lastyear_image_url
      t.text :awards_2_conditions
      t.string :why_1_title
      t.text :why_1_text
      t.string :why_2_title
      t.string :why_3_title
      t.string :why_4_title
      t.string :why_2_text
      t.string :why_3_text
      t.string :why_4_text
      t.text :contractors_buildup
      t.text :contractors_breakdown
      t.text :exhibiting_text
      t.string :main_phone
      t.string :main_email
      t.string :main_address
      t.string :main_errata
      t.text :last_year_text
      t.text :cookie_info
      t.text :livestock_about_nds
      t.text :livestock_about_charolais
      t.text :livestock_about_bb
      t.text :livestock_about_aa
      t.text :livestock_about_lleyn
      t.text :livestock_about_all
      t.text :tickets_text
      t.text :whyvisit_text
      t.string :welcome_title
      t.string :welcome_1_label
      t.string :welcome_2_label
      t.string :welcome_3_label
      t.string :welcome_4_label
      t.string :welcome_5_label
      t.string :welcome_6_label
      t.string :welcome_1_icon
      t.string :welcome_2_icon
      t.string :welcome_3_icon
      t.string :welcome_4_icon
      t.string :welcome_5_icon
      t.string :welcome_6_icon
      t.text :welcome_1_text
      t.string :welcome_2_header
      t.string :welcome_3_header
      t.string :welcome_4_header
      t.string :welcome_5_header
      t.string :welcome_6_header
      t.text :welcome_2_text
      t.text :welcome_3_text
      t.text :welcome_4_text
      t.text :welcome_5_text
      t.text :welcome_6_text
      t.text :whatson_ah_text
      t.text :whatson_bm_text
      t.text :whatson_dr_text
      t.text :whatson_ff_text
      t.text :whatson_genetics_text
      t.text :whatson_hs_text
      t.text :whatson_lem_text
      t.text :whatson_mh_text
      t.text :whatson_ml_text
      t.text :whatson_mm_text
      t.text :whatson_si_text
      t.text :whatson_farmsec_text
      t.text :whatson_forfield_text
      t.text :whatson_pigpoult_text
      t.text :whatson_lameprev_text
      t.text :whatson_foottrim_text
      t.text :whatson_export_text
      t.text :whatson_careers_text
      t.text :whatson_dairypro_text
      t.text :whatson_nds_text
      t.text :whatson_ncs_text
      t.text :whatson_nbbs_text
      t.text :whatson_nlsc_text
      t.text :whatson_societies_text
      t.text :whatson_naas_text
      t.text :whatson_busdebates_text
      t.text :whatson_farmhealth_text
      t.text :whatson_feedsci_text
      t.text :whatson_fourfour_text
      t.text :whatson_utv_text

      t.timestamps
    end
  end
end
